/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as ServicosRouteImport } from './routes/Servicos'
import { Route as QuemSomosRouteImport } from './routes/QuemSomos'
import { Route as ContatoRouteImport } from './routes/Contato'
import { Route as AtendimentoRouteImport } from './routes/Atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestaoIndexRouteImport } from './routes/gestao.index'
import { Route as GestaoPacientesRouteImport } from './routes/gestao.pacientes'
import { Route as GestaoLoginRouteImport } from './routes/gestao.login'
import { Route as GestaoFinanceiroRouteImport } from './routes/gestao.financeiro'
import { Route as GestaoDashboardRouteImport } from './routes/gestao.dashboard'
import { Route as GestaoContratosRouteImport } from './routes/gestao.contratos'
import { Route as GestaoConfiguracoesRouteImport } from './routes/gestao.configuracoes'
import { Route as GestaoAgendaRouteImport } from './routes/gestao.agenda'
import { Route as GestaoPacientesIndexRouteImport } from './routes/gestao.pacientes.index'
import { Route as GestaoSiteServicosRouteImport } from './routes/gestao.site.servicos'
import { Route as GestaoSiteLayoutRouteImport } from './routes/gestao.site.layout'
import { Route as GestaoSiteEquipeRouteImport } from './routes/gestao.site.equipe'
import { Route as GestaoSiteDepoimentosRouteImport } from './routes/gestao.site.depoimentos'
import { Route as GestaoPacientesNovoRouteImport } from './routes/gestao.pacientes.novo'
import { Route as GestaoPacientesIdRouteImport } from './routes/gestao.pacientes.$id'
import { Route as GestaoSiteLayoutIndexRouteImport } from './routes/gestao.site.layout.index'
import { Route as GestaoSiteLayoutSecoesRouteImport } from './routes/gestao.site.layout.secoes'
import { Route as GestaoSiteLayoutRodapeRouteImport } from './routes/gestao.site.layout.rodape'
import { Route as GestaoSiteLayoutHeroRouteImport } from './routes/gestao.site.layout.hero'
import { Route as ApiPublicFileProxySplatRouteImport } from './routes/api/public/file-proxy.$'

const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/Servicos',
  path: '/Servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/QuemSomos',
  path: '/QuemSomos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/Contato',
  path: '/Contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/Atendimento',
  path: '/Atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoIndexRoute = GestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPacientesRoute = GestaoPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoLoginRoute = GestaoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoFinanceiroRoute = GestaoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoDashboardRoute = GestaoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoContratosRoute = GestaoContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoConfiguracoesRoute = GestaoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoAgendaRoute = GestaoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPacientesIndexRoute = GestaoPacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoPacientesRoute,
} as any)
const GestaoSiteServicosRoute = GestaoSiteServicosRouteImport.update({
  id: '/site/servicos',
  path: '/site/servicos',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoSiteLayoutRoute = GestaoSiteLayoutRouteImport.update({
  id: '/site/layout',
  path: '/site/layout',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoSiteEquipeRoute = GestaoSiteEquipeRouteImport.update({
  id: '/site/equipe',
  path: '/site/equipe',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoSiteDepoimentosRoute = GestaoSiteDepoimentosRouteImport.update({
  id: '/site/depoimentos',
  path: '/site/depoimentos',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPacientesNovoRoute = GestaoPacientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => GestaoPacientesRoute,
} as any)
const GestaoPacientesIdRoute = GestaoPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GestaoPacientesRoute,
} as any)
const GestaoSiteLayoutIndexRoute = GestaoSiteLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoSiteLayoutRoute,
} as any)
const GestaoSiteLayoutSecoesRoute = GestaoSiteLayoutSecoesRouteImport.update({
  id: '/secoes',
  path: '/secoes',
  getParentRoute: () => GestaoSiteLayoutRoute,
} as any)
const GestaoSiteLayoutRodapeRoute = GestaoSiteLayoutRodapeRouteImport.update({
  id: '/rodape',
  path: '/rodape',
  getParentRoute: () => GestaoSiteLayoutRoute,
} as any)
const GestaoSiteLayoutHeroRoute = GestaoSiteLayoutHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => GestaoSiteLayoutRoute,
} as any)
const ApiPublicFileProxySplatRoute = ApiPublicFileProxySplatRouteImport.update({
  id: '/api/public/file-proxy/$',
  path: '/api/public/file-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/gestao/agenda': typeof GestaoAgendaRoute
  '/gestao/configuracoes': typeof GestaoConfiguracoesRoute
  '/gestao/contratos': typeof GestaoContratosRoute
  '/gestao/dashboard': typeof GestaoDashboardRoute
  '/gestao/financeiro': typeof GestaoFinanceiroRoute
  '/gestao/login': typeof GestaoLoginRoute
  '/gestao/pacientes': typeof GestaoPacientesRouteWithChildren
  '/gestao/': typeof GestaoIndexRoute
  '/gestao/pacientes/$id': typeof GestaoPacientesIdRoute
  '/gestao/pacientes/novo': typeof GestaoPacientesNovoRoute
  '/gestao/site/depoimentos': typeof GestaoSiteDepoimentosRoute
  '/gestao/site/equipe': typeof GestaoSiteEquipeRoute
  '/gestao/site/layout': typeof GestaoSiteLayoutRouteWithChildren
  '/gestao/site/servicos': typeof GestaoSiteServicosRoute
  '/gestao/pacientes/': typeof GestaoPacientesIndexRoute
  '/api/public/file-proxy/$': typeof ApiPublicFileProxySplatRoute
  '/gestao/site/layout/hero': typeof GestaoSiteLayoutHeroRoute
  '/gestao/site/layout/rodape': typeof GestaoSiteLayoutRodapeRoute
  '/gestao/site/layout/secoes': typeof GestaoSiteLayoutSecoesRoute
  '/gestao/site/layout/': typeof GestaoSiteLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/gestao/agenda': typeof GestaoAgendaRoute
  '/gestao/configuracoes': typeof GestaoConfiguracoesRoute
  '/gestao/contratos': typeof GestaoContratosRoute
  '/gestao/dashboard': typeof GestaoDashboardRoute
  '/gestao/financeiro': typeof GestaoFinanceiroRoute
  '/gestao/login': typeof GestaoLoginRoute
  '/gestao': typeof GestaoIndexRoute
  '/gestao/pacientes/$id': typeof GestaoPacientesIdRoute
  '/gestao/pacientes/novo': typeof GestaoPacientesNovoRoute
  '/gestao/site/depoimentos': typeof GestaoSiteDepoimentosRoute
  '/gestao/site/equipe': typeof GestaoSiteEquipeRoute
  '/gestao/site/servicos': typeof GestaoSiteServicosRoute
  '/gestao/pacientes': typeof GestaoPacientesIndexRoute
  '/api/public/file-proxy/$': typeof ApiPublicFileProxySplatRoute
  '/gestao/site/layout/hero': typeof GestaoSiteLayoutHeroRoute
  '/gestao/site/layout/rodape': typeof GestaoSiteLayoutRodapeRoute
  '/gestao/site/layout/secoes': typeof GestaoSiteLayoutSecoesRoute
  '/gestao/site/layout': typeof GestaoSiteLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/gestao': typeof GestaoRouteWithChildren
  '/gestao/agenda': typeof GestaoAgendaRoute
  '/gestao/configuracoes': typeof GestaoConfiguracoesRoute
  '/gestao/contratos': typeof GestaoContratosRoute
  '/gestao/dashboard': typeof GestaoDashboardRoute
  '/gestao/financeiro': typeof GestaoFinanceiroRoute
  '/gestao/login': typeof GestaoLoginRoute
  '/gestao/pacientes': typeof GestaoPacientesRouteWithChildren
  '/gestao/': typeof GestaoIndexRoute
  '/gestao/pacientes/$id': typeof GestaoPacientesIdRoute
  '/gestao/pacientes/novo': typeof GestaoPacientesNovoRoute
  '/gestao/site/depoimentos': typeof GestaoSiteDepoimentosRoute
  '/gestao/site/equipe': typeof GestaoSiteEquipeRoute
  '/gestao/site/layout': typeof GestaoSiteLayoutRouteWithChildren
  '/gestao/site/servicos': typeof GestaoSiteServicosRoute
  '/gestao/pacientes/': typeof GestaoPacientesIndexRoute
  '/api/public/file-proxy/$': typeof ApiPublicFileProxySplatRoute
  '/gestao/site/layout/hero': typeof GestaoSiteLayoutHeroRoute
  '/gestao/site/layout/rodape': typeof GestaoSiteLayoutRodapeRoute
  '/gestao/site/layout/secoes': typeof GestaoSiteLayoutSecoesRoute
  '/gestao/site/layout/': typeof GestaoSiteLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/QuemSomos'
    | '/Servicos'
    | '/gestao'
    | '/gestao/agenda'
    | '/gestao/configuracoes'
    | '/gestao/contratos'
    | '/gestao/dashboard'
    | '/gestao/financeiro'
    | '/gestao/login'
    | '/gestao/pacientes'
    | '/gestao/'
    | '/gestao/pacientes/$id'
    | '/gestao/pacientes/novo'
    | '/gestao/site/depoimentos'
    | '/gestao/site/equipe'
    | '/gestao/site/layout'
    | '/gestao/site/servicos'
    | '/gestao/pacientes/'
    | '/api/public/file-proxy/$'
    | '/gestao/site/layout/hero'
    | '/gestao/site/layout/rodape'
    | '/gestao/site/layout/secoes'
    | '/gestao/site/layout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/QuemSomos'
    | '/Servicos'
    | '/gestao/agenda'
    | '/gestao/configuracoes'
    | '/gestao/contratos'
    | '/gestao/dashboard'
    | '/gestao/financeiro'
    | '/gestao/login'
    | '/gestao'
    | '/gestao/pacientes/$id'
    | '/gestao/pacientes/novo'
    | '/gestao/site/depoimentos'
    | '/gestao/site/equipe'
    | '/gestao/site/servicos'
    | '/gestao/pacientes'
    | '/api/public/file-proxy/$'
    | '/gestao/site/layout/hero'
    | '/gestao/site/layout/rodape'
    | '/gestao/site/layout/secoes'
    | '/gestao/site/layout'
  id:
    | '__root__'
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/QuemSomos'
    | '/Servicos'
    | '/gestao'
    | '/gestao/agenda'
    | '/gestao/configuracoes'
    | '/gestao/contratos'
    | '/gestao/dashboard'
    | '/gestao/financeiro'
    | '/gestao/login'
    | '/gestao/pacientes'
    | '/gestao/'
    | '/gestao/pacientes/$id'
    | '/gestao/pacientes/novo'
    | '/gestao/site/depoimentos'
    | '/gestao/site/equipe'
    | '/gestao/site/layout'
    | '/gestao/site/servicos'
    | '/gestao/pacientes/'
    | '/api/public/file-proxy/$'
    | '/gestao/site/layout/hero'
    | '/gestao/site/layout/rodape'
    | '/gestao/site/layout/secoes'
    | '/gestao/site/layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ContatoRoute: typeof ContatoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
  GestaoRoute: typeof GestaoRouteWithChildren
  ApiPublicFileProxySplatRoute: typeof ApiPublicFileProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Servicos': {
      id: '/Servicos'
      path: '/Servicos'
      fullPath: '/Servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/QuemSomos': {
      id: '/QuemSomos'
      path: '/QuemSomos'
      fullPath: '/QuemSomos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contato': {
      id: '/Contato'
      path: '/Contato'
      fullPath: '/Contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Atendimento': {
      id: '/Atendimento'
      path: '/Atendimento'
      fullPath: '/Atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/': {
      id: '/gestao/'
      path: '/'
      fullPath: '/gestao/'
      preLoaderRoute: typeof GestaoIndexRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/pacientes': {
      id: '/gestao/pacientes'
      path: '/pacientes'
      fullPath: '/gestao/pacientes'
      preLoaderRoute: typeof GestaoPacientesRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/login': {
      id: '/gestao/login'
      path: '/login'
      fullPath: '/gestao/login'
      preLoaderRoute: typeof GestaoLoginRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/financeiro': {
      id: '/gestao/financeiro'
      path: '/financeiro'
      fullPath: '/gestao/financeiro'
      preLoaderRoute: typeof GestaoFinanceiroRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/dashboard': {
      id: '/gestao/dashboard'
      path: '/dashboard'
      fullPath: '/gestao/dashboard'
      preLoaderRoute: typeof GestaoDashboardRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/contratos': {
      id: '/gestao/contratos'
      path: '/contratos'
      fullPath: '/gestao/contratos'
      preLoaderRoute: typeof GestaoContratosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/configuracoes': {
      id: '/gestao/configuracoes'
      path: '/configuracoes'
      fullPath: '/gestao/configuracoes'
      preLoaderRoute: typeof GestaoConfiguracoesRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/agenda': {
      id: '/gestao/agenda'
      path: '/agenda'
      fullPath: '/gestao/agenda'
      preLoaderRoute: typeof GestaoAgendaRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/pacientes/': {
      id: '/gestao/pacientes/'
      path: '/'
      fullPath: '/gestao/pacientes/'
      preLoaderRoute: typeof GestaoPacientesIndexRouteImport
      parentRoute: typeof GestaoPacientesRoute
    }
    '/gestao/site/servicos': {
      id: '/gestao/site/servicos'
      path: '/site/servicos'
      fullPath: '/gestao/site/servicos'
      preLoaderRoute: typeof GestaoSiteServicosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/site/layout': {
      id: '/gestao/site/layout'
      path: '/site/layout'
      fullPath: '/gestao/site/layout'
      preLoaderRoute: typeof GestaoSiteLayoutRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/site/equipe': {
      id: '/gestao/site/equipe'
      path: '/site/equipe'
      fullPath: '/gestao/site/equipe'
      preLoaderRoute: typeof GestaoSiteEquipeRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/site/depoimentos': {
      id: '/gestao/site/depoimentos'
      path: '/site/depoimentos'
      fullPath: '/gestao/site/depoimentos'
      preLoaderRoute: typeof GestaoSiteDepoimentosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/pacientes/novo': {
      id: '/gestao/pacientes/novo'
      path: '/novo'
      fullPath: '/gestao/pacientes/novo'
      preLoaderRoute: typeof GestaoPacientesNovoRouteImport
      parentRoute: typeof GestaoPacientesRoute
    }
    '/gestao/pacientes/$id': {
      id: '/gestao/pacientes/$id'
      path: '/$id'
      fullPath: '/gestao/pacientes/$id'
      preLoaderRoute: typeof GestaoPacientesIdRouteImport
      parentRoute: typeof GestaoPacientesRoute
    }
    '/gestao/site/layout/': {
      id: '/gestao/site/layout/'
      path: '/'
      fullPath: '/gestao/site/layout/'
      preLoaderRoute: typeof GestaoSiteLayoutIndexRouteImport
      parentRoute: typeof GestaoSiteLayoutRoute
    }
    '/gestao/site/layout/secoes': {
      id: '/gestao/site/layout/secoes'
      path: '/secoes'
      fullPath: '/gestao/site/layout/secoes'
      preLoaderRoute: typeof GestaoSiteLayoutSecoesRouteImport
      parentRoute: typeof GestaoSiteLayoutRoute
    }
    '/gestao/site/layout/rodape': {
      id: '/gestao/site/layout/rodape'
      path: '/rodape'
      fullPath: '/gestao/site/layout/rodape'
      preLoaderRoute: typeof GestaoSiteLayoutRodapeRouteImport
      parentRoute: typeof GestaoSiteLayoutRoute
    }
    '/gestao/site/layout/hero': {
      id: '/gestao/site/layout/hero'
      path: '/hero'
      fullPath: '/gestao/site/layout/hero'
      preLoaderRoute: typeof GestaoSiteLayoutHeroRouteImport
      parentRoute: typeof GestaoSiteLayoutRoute
    }
    '/api/public/file-proxy/$': {
      id: '/api/public/file-proxy/$'
      path: '/api/public/file-proxy/$'
      fullPath: '/api/public/file-proxy/$'
      preLoaderRoute: typeof ApiPublicFileProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GestaoPacientesRouteChildren {
  GestaoPacientesIdRoute: typeof GestaoPacientesIdRoute
  GestaoPacientesNovoRoute: typeof GestaoPacientesNovoRoute
  GestaoPacientesIndexRoute: typeof GestaoPacientesIndexRoute
}

const GestaoPacientesRouteChildren: GestaoPacientesRouteChildren = {
  GestaoPacientesIdRoute: GestaoPacientesIdRoute,
  GestaoPacientesNovoRoute: GestaoPacientesNovoRoute,
  GestaoPacientesIndexRoute: GestaoPacientesIndexRoute,
}

const GestaoPacientesRouteWithChildren = GestaoPacientesRoute._addFileChildren(
  GestaoPacientesRouteChildren,
)

interface GestaoSiteLayoutRouteChildren {
  GestaoSiteLayoutHeroRoute: typeof GestaoSiteLayoutHeroRoute
  GestaoSiteLayoutRodapeRoute: typeof GestaoSiteLayoutRodapeRoute
  GestaoSiteLayoutSecoesRoute: typeof GestaoSiteLayoutSecoesRoute
  GestaoSiteLayoutIndexRoute: typeof GestaoSiteLayoutIndexRoute
}

const GestaoSiteLayoutRouteChildren: GestaoSiteLayoutRouteChildren = {
  GestaoSiteLayoutHeroRoute: GestaoSiteLayoutHeroRoute,
  GestaoSiteLayoutRodapeRoute: GestaoSiteLayoutRodapeRoute,
  GestaoSiteLayoutSecoesRoute: GestaoSiteLayoutSecoesRoute,
  GestaoSiteLayoutIndexRoute: GestaoSiteLayoutIndexRoute,
}

const GestaoSiteLayoutRouteWithChildren =
  GestaoSiteLayoutRoute._addFileChildren(GestaoSiteLayoutRouteChildren)

interface GestaoRouteChildren {
  GestaoAgendaRoute: typeof GestaoAgendaRoute
  GestaoConfiguracoesRoute: typeof GestaoConfiguracoesRoute
  GestaoContratosRoute: typeof GestaoContratosRoute
  GestaoDashboardRoute: typeof GestaoDashboardRoute
  GestaoFinanceiroRoute: typeof GestaoFinanceiroRoute
  GestaoLoginRoute: typeof GestaoLoginRoute
  GestaoPacientesRoute: typeof GestaoPacientesRouteWithChildren
  GestaoIndexRoute: typeof GestaoIndexRoute
  GestaoSiteDepoimentosRoute: typeof GestaoSiteDepoimentosRoute
  GestaoSiteEquipeRoute: typeof GestaoSiteEquipeRoute
  GestaoSiteLayoutRoute: typeof GestaoSiteLayoutRouteWithChildren
  GestaoSiteServicosRoute: typeof GestaoSiteServicosRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoAgendaRoute: GestaoAgendaRoute,
  GestaoConfiguracoesRoute: GestaoConfiguracoesRoute,
  GestaoContratosRoute: GestaoContratosRoute,
  GestaoDashboardRoute: GestaoDashboardRoute,
  GestaoFinanceiroRoute: GestaoFinanceiroRoute,
  GestaoLoginRoute: GestaoLoginRoute,
  GestaoPacientesRoute: GestaoPacientesRouteWithChildren,
  GestaoIndexRoute: GestaoIndexRoute,
  GestaoSiteDepoimentosRoute: GestaoSiteDepoimentosRoute,
  GestaoSiteEquipeRoute: GestaoSiteEquipeRoute,
  GestaoSiteLayoutRoute: GestaoSiteLayoutRouteWithChildren,
  GestaoSiteServicosRoute: GestaoSiteServicosRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ContatoRoute: ContatoRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
  GestaoRoute: GestaoRouteWithChildren,
  ApiPublicFileProxySplatRoute: ApiPublicFileProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
