/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ServicosRouteImport } from './routes/Servicos'
import { Route as QuemSomosRouteImport } from './routes/QuemSomos'
import { Route as ParticularRouteImport } from './routes/Particular'
import { Route as ContatoRouteImport } from './routes/Contato'
import { Route as AtendimentoRouteImport } from './routes/Atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminDepoimentosRouteImport } from './routes/admin.depoimentos'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/Servicos',
  path: '/Servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/QuemSomos',
  path: '/QuemSomos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticularRoute = ParticularRouteImport.update({
  id: '/Particular',
  path: '/Particular',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/Contato',
  path: '/Contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/Atendimento',
  path: '/Atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepoimentosRoute = AdminDepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/Particular': typeof ParticularRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/Particular': typeof ParticularRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/Particular': typeof ParticularRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/Particular'
    | '/QuemSomos'
    | '/Servicos'
    | '/admin'
    | '/admin/depoimentos'
    | '/admin/equipe'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/Particular'
    | '/QuemSomos'
    | '/Servicos'
    | '/admin/depoimentos'
    | '/admin/equipe'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/Particular'
    | '/QuemSomos'
    | '/Servicos'
    | '/admin'
    | '/admin/depoimentos'
    | '/admin/equipe'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ContatoRoute: typeof ContatoRoute
  ParticularRoute: typeof ParticularRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Servicos': {
      id: '/Servicos'
      path: '/Servicos'
      fullPath: '/Servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/QuemSomos': {
      id: '/QuemSomos'
      path: '/QuemSomos'
      fullPath: '/QuemSomos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Particular': {
      id: '/Particular'
      path: '/Particular'
      fullPath: '/Particular'
      preLoaderRoute: typeof ParticularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contato': {
      id: '/Contato'
      path: '/Contato'
      fullPath: '/Contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Atendimento': {
      id: '/Atendimento'
      path: '/Atendimento'
      fullPath: '/Atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/depoimentos': {
      id: '/admin/depoimentos'
      path: '/depoimentos'
      fullPath: '/admin/depoimentos'
      preLoaderRoute: typeof AdminDepoimentosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDepoimentosRoute: typeof AdminDepoimentosRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepoimentosRoute: AdminDepoimentosRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ContatoRoute: ContatoRoute,
  ParticularRoute: ParticularRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
