/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ServicosRouteImport } from './routes/Servicos'
import { Route as QuemSomosRouteImport } from './routes/QuemSomos'
import { Route as ParticularRouteImport } from './routes/Particular'
import { Route as ContatoRouteImport } from './routes/Contato'
import { Route as AtendimentoRouteImport } from './routes/Atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestaoIndexRouteImport } from './routes/gestao.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GestaoPacientesRouteImport } from './routes/gestao.pacientes'
import { Route as GestaoLoginRouteImport } from './routes/gestao.login'
import { Route as GestaoFinanceiroRouteImport } from './routes/gestao.financeiro'
import { Route as GestaoDashboardRouteImport } from './routes/gestao.dashboard'
import { Route as GestaoContratosRouteImport } from './routes/gestao.contratos'
import { Route as GestaoConfiguracoesRouteImport } from './routes/gestao.configuracoes'
import { Route as GestaoAgendaRouteImport } from './routes/gestao.agenda'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminDepoimentosRouteImport } from './routes/admin.depoimentos'
import { Route as GestaoPacientesIndexRouteImport } from './routes/gestao.pacientes.index'
import { Route as GestaoSiteEquipeRouteImport } from './routes/gestao.site.equipe'
import { Route as GestaoSiteDepoimentosRouteImport } from './routes/gestao.site.depoimentos'
import { Route as GestaoPacientesIdRouteImport } from './routes/gestao.pacientes.$id'

const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/Servicos',
  path: '/Servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/QuemSomos',
  path: '/QuemSomos',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticularRoute = ParticularRouteImport.update({
  id: '/Particular',
  path: '/Particular',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/Contato',
  path: '/Contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/Atendimento',
  path: '/Atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoIndexRoute = GestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GestaoPacientesRoute = GestaoPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoLoginRoute = GestaoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoFinanceiroRoute = GestaoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoDashboardRoute = GestaoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoContratosRoute = GestaoContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoConfiguracoesRoute = GestaoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoAgendaRoute = GestaoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => GestaoRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepoimentosRoute = AdminDepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => AdminRoute,
} as any)
const GestaoPacientesIndexRoute = GestaoPacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoPacientesRoute,
} as any)
const GestaoSiteEquipeRoute = GestaoSiteEquipeRouteImport.update({
  id: '/site/equipe',
  path: '/site/equipe',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoSiteDepoimentosRoute = GestaoSiteDepoimentosRouteImport.update({
  id: '/site/depoimentos',
  path: '/site/depoimentos',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPacientesIdRoute = GestaoPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GestaoPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/Particular': typeof ParticularRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/admin': typeof AdminRouteWithChildren
  '/gestao': typeof GestaoRouteWithChildren
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/gestao/agenda': typeof GestaoAgendaRoute
  '/gestao/configuracoes': typeof GestaoConfiguracoesRoute
  '/gestao/contratos': typeof GestaoContratosRoute
  '/gestao/dashboard': typeof GestaoDashboardRoute
  '/gestao/financeiro': typeof GestaoFinanceiroRoute
  '/gestao/login': typeof GestaoLoginRoute
  '/gestao/pacientes': typeof GestaoPacientesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/gestao/': typeof GestaoIndexRoute
  '/gestao/pacientes/$id': typeof GestaoPacientesIdRoute
  '/gestao/site/depoimentos': typeof GestaoSiteDepoimentosRoute
  '/gestao/site/equipe': typeof GestaoSiteEquipeRoute
  '/gestao/pacientes/': typeof GestaoPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/Particular': typeof ParticularRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/gestao/agenda': typeof GestaoAgendaRoute
  '/gestao/configuracoes': typeof GestaoConfiguracoesRoute
  '/gestao/contratos': typeof GestaoContratosRoute
  '/gestao/dashboard': typeof GestaoDashboardRoute
  '/gestao/financeiro': typeof GestaoFinanceiroRoute
  '/gestao/login': typeof GestaoLoginRoute
  '/admin': typeof AdminIndexRoute
  '/gestao': typeof GestaoIndexRoute
  '/gestao/pacientes/$id': typeof GestaoPacientesIdRoute
  '/gestao/site/depoimentos': typeof GestaoSiteDepoimentosRoute
  '/gestao/site/equipe': typeof GestaoSiteEquipeRoute
  '/gestao/pacientes': typeof GestaoPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Atendimento': typeof AtendimentoRoute
  '/Contato': typeof ContatoRoute
  '/Particular': typeof ParticularRoute
  '/QuemSomos': typeof QuemSomosRoute
  '/Servicos': typeof ServicosRoute
  '/admin': typeof AdminRouteWithChildren
  '/gestao': typeof GestaoRouteWithChildren
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/gestao/agenda': typeof GestaoAgendaRoute
  '/gestao/configuracoes': typeof GestaoConfiguracoesRoute
  '/gestao/contratos': typeof GestaoContratosRoute
  '/gestao/dashboard': typeof GestaoDashboardRoute
  '/gestao/financeiro': typeof GestaoFinanceiroRoute
  '/gestao/login': typeof GestaoLoginRoute
  '/gestao/pacientes': typeof GestaoPacientesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/gestao/': typeof GestaoIndexRoute
  '/gestao/pacientes/$id': typeof GestaoPacientesIdRoute
  '/gestao/site/depoimentos': typeof GestaoSiteDepoimentosRoute
  '/gestao/site/equipe': typeof GestaoSiteEquipeRoute
  '/gestao/pacientes/': typeof GestaoPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/Particular'
    | '/QuemSomos'
    | '/Servicos'
    | '/admin'
    | '/gestao'
    | '/admin/depoimentos'
    | '/admin/equipe'
    | '/admin/login'
    | '/gestao/agenda'
    | '/gestao/configuracoes'
    | '/gestao/contratos'
    | '/gestao/dashboard'
    | '/gestao/financeiro'
    | '/gestao/login'
    | '/gestao/pacientes'
    | '/admin/'
    | '/gestao/'
    | '/gestao/pacientes/$id'
    | '/gestao/site/depoimentos'
    | '/gestao/site/equipe'
    | '/gestao/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/Particular'
    | '/QuemSomos'
    | '/Servicos'
    | '/admin/depoimentos'
    | '/admin/equipe'
    | '/admin/login'
    | '/gestao/agenda'
    | '/gestao/configuracoes'
    | '/gestao/contratos'
    | '/gestao/dashboard'
    | '/gestao/financeiro'
    | '/gestao/login'
    | '/admin'
    | '/gestao'
    | '/gestao/pacientes/$id'
    | '/gestao/site/depoimentos'
    | '/gestao/site/equipe'
    | '/gestao/pacientes'
  id:
    | '__root__'
    | '/'
    | '/Atendimento'
    | '/Contato'
    | '/Particular'
    | '/QuemSomos'
    | '/Servicos'
    | '/admin'
    | '/gestao'
    | '/admin/depoimentos'
    | '/admin/equipe'
    | '/admin/login'
    | '/gestao/agenda'
    | '/gestao/configuracoes'
    | '/gestao/contratos'
    | '/gestao/dashboard'
    | '/gestao/financeiro'
    | '/gestao/login'
    | '/gestao/pacientes'
    | '/admin/'
    | '/gestao/'
    | '/gestao/pacientes/$id'
    | '/gestao/site/depoimentos'
    | '/gestao/site/equipe'
    | '/gestao/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ContatoRoute: typeof ContatoRoute
  ParticularRoute: typeof ParticularRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
  AdminRoute: typeof AdminRouteWithChildren
  GestaoRoute: typeof GestaoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Servicos': {
      id: '/Servicos'
      path: '/Servicos'
      fullPath: '/Servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/QuemSomos': {
      id: '/QuemSomos'
      path: '/QuemSomos'
      fullPath: '/QuemSomos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Particular': {
      id: '/Particular'
      path: '/Particular'
      fullPath: '/Particular'
      preLoaderRoute: typeof ParticularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contato': {
      id: '/Contato'
      path: '/Contato'
      fullPath: '/Contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Atendimento': {
      id: '/Atendimento'
      path: '/Atendimento'
      fullPath: '/Atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/': {
      id: '/gestao/'
      path: '/'
      fullPath: '/gestao/'
      preLoaderRoute: typeof GestaoIndexRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/gestao/pacientes': {
      id: '/gestao/pacientes'
      path: '/pacientes'
      fullPath: '/gestao/pacientes'
      preLoaderRoute: typeof GestaoPacientesRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/login': {
      id: '/gestao/login'
      path: '/login'
      fullPath: '/gestao/login'
      preLoaderRoute: typeof GestaoLoginRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/financeiro': {
      id: '/gestao/financeiro'
      path: '/financeiro'
      fullPath: '/gestao/financeiro'
      preLoaderRoute: typeof GestaoFinanceiroRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/dashboard': {
      id: '/gestao/dashboard'
      path: '/dashboard'
      fullPath: '/gestao/dashboard'
      preLoaderRoute: typeof GestaoDashboardRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/contratos': {
      id: '/gestao/contratos'
      path: '/contratos'
      fullPath: '/gestao/contratos'
      preLoaderRoute: typeof GestaoContratosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/configuracoes': {
      id: '/gestao/configuracoes'
      path: '/configuracoes'
      fullPath: '/gestao/configuracoes'
      preLoaderRoute: typeof GestaoConfiguracoesRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/agenda': {
      id: '/gestao/agenda'
      path: '/agenda'
      fullPath: '/gestao/agenda'
      preLoaderRoute: typeof GestaoAgendaRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/depoimentos': {
      id: '/admin/depoimentos'
      path: '/depoimentos'
      fullPath: '/admin/depoimentos'
      preLoaderRoute: typeof AdminDepoimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/gestao/pacientes/': {
      id: '/gestao/pacientes/'
      path: '/'
      fullPath: '/gestao/pacientes/'
      preLoaderRoute: typeof GestaoPacientesIndexRouteImport
      parentRoute: typeof GestaoPacientesRoute
    }
    '/gestao/site/equipe': {
      id: '/gestao/site/equipe'
      path: '/site/equipe'
      fullPath: '/gestao/site/equipe'
      preLoaderRoute: typeof GestaoSiteEquipeRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/site/depoimentos': {
      id: '/gestao/site/depoimentos'
      path: '/site/depoimentos'
      fullPath: '/gestao/site/depoimentos'
      preLoaderRoute: typeof GestaoSiteDepoimentosRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/pacientes/$id': {
      id: '/gestao/pacientes/$id'
      path: '/$id'
      fullPath: '/gestao/pacientes/$id'
      preLoaderRoute: typeof GestaoPacientesIdRouteImport
      parentRoute: typeof GestaoPacientesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDepoimentosRoute: typeof AdminDepoimentosRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepoimentosRoute: AdminDepoimentosRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GestaoPacientesRouteChildren {
  GestaoPacientesIdRoute: typeof GestaoPacientesIdRoute
  GestaoPacientesIndexRoute: typeof GestaoPacientesIndexRoute
}

const GestaoPacientesRouteChildren: GestaoPacientesRouteChildren = {
  GestaoPacientesIdRoute: GestaoPacientesIdRoute,
  GestaoPacientesIndexRoute: GestaoPacientesIndexRoute,
}

const GestaoPacientesRouteWithChildren = GestaoPacientesRoute._addFileChildren(
  GestaoPacientesRouteChildren,
)

interface GestaoRouteChildren {
  GestaoAgendaRoute: typeof GestaoAgendaRoute
  GestaoConfiguracoesRoute: typeof GestaoConfiguracoesRoute
  GestaoContratosRoute: typeof GestaoContratosRoute
  GestaoDashboardRoute: typeof GestaoDashboardRoute
  GestaoFinanceiroRoute: typeof GestaoFinanceiroRoute
  GestaoLoginRoute: typeof GestaoLoginRoute
  GestaoPacientesRoute: typeof GestaoPacientesRouteWithChildren
  GestaoIndexRoute: typeof GestaoIndexRoute
  GestaoSiteDepoimentosRoute: typeof GestaoSiteDepoimentosRoute
  GestaoSiteEquipeRoute: typeof GestaoSiteEquipeRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoAgendaRoute: GestaoAgendaRoute,
  GestaoConfiguracoesRoute: GestaoConfiguracoesRoute,
  GestaoContratosRoute: GestaoContratosRoute,
  GestaoDashboardRoute: GestaoDashboardRoute,
  GestaoFinanceiroRoute: GestaoFinanceiroRoute,
  GestaoLoginRoute: GestaoLoginRoute,
  GestaoPacientesRoute: GestaoPacientesRouteWithChildren,
  GestaoIndexRoute: GestaoIndexRoute,
  GestaoSiteDepoimentosRoute: GestaoSiteDepoimentosRoute,
  GestaoSiteEquipeRoute: GestaoSiteEquipeRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ContatoRoute: ContatoRoute,
  ParticularRoute: ParticularRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
  AdminRoute: AdminRouteWithChildren,
  GestaoRoute: GestaoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
